### ISSUE TITLE
bamtools todo

### ISSUE THREAD

**Issue by cokelaer** [sequana/sequana#384]
- [x] bam_analysis_to_json : use indent and sort keys
- [x] check all docstrings
- [x] tests
- [x] filter_length -> use two thresholds
